name: Build turtle file

on: [push]

jobs:
  build-linux:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.9
      uses: actions/setup-python@v3
      with:
        python-version: 3.9
    - name: Add conda to system path
      run: |
        # $CONDA is an environment variable pointing to the root of the miniconda directory
        echo $CONDA/bin >> $GITHUB_PATH
    - name: Install dependencies
      run: |
        conda install pandas numpy xlsxwriter openpyxl
    - name: Build
      run: |
        python3 csv_to_turtle.py
    - name: Release & Assets
      uses: johnwbyrd/update-release@v1.0.0
      with:
        release: latest
        token: ${{ secrets.GITHUB_TOKEN }}
        body: This is an automated release.
        files: ./turtle/unit_test3.ttl
